// Tracks 1–100 mirror Live_Laugh_Love.csv in playlist order.
// The final eight are explicitly retained additions.
const soundtrack = (id, title, artist, themes) =>
  Object.freeze({ id, title, artist, themes: Object.freeze(themes.split(" ")) });

window.SOUNDTRACKS = Object.freeze([
  soundtrack("1qbmS6ep2hbBRaEZFpn7BX", "Man I Need", "Olivia Dean", "love connection hope"),
  soundtrack("1mX96thG2hGyuyAz94Q5tk", "Mmmbop", "Hanson", "love connection presence"),
  soundtrack("7ewI4ZKxRXrkESHB8eGBnO", "Fire and the Flood", "Vance Joy", "love devotion connection"),
  soundtrack("3m9MKNTdPmsKJRqrhqQnhW", "Imagine - Acoustic", "Ben Platt", "love devotion wonder"),
  soundtrack("3vOmmLuvEUgGaVuRsCs2QF", "I Was Made For Loving You", "Tori Kelly, Ed Sheeran", "love devotion connection"),
  soundtrack("2C9ePPz58he8jmYEod9pvT", "Isn't She Lovely - Acoustic", "Callum J Wright", "love appreciation joy"),
  soundtrack("0HEmnAUT8PHznIAAmVXqFJ", "Faith - Remastered", "George Michael", "hope love courage"),
  soundtrack("46eu3SBuFCXWsPT39Yg3tJ", "Don't Stop 'Til You Get Enough", "Michael Jackson", "perseverance joy love"),
  soundtrack("2FQrifJ1N335Ljm3TjTVVf", "A Bar Song (Tipsy)", "Shaboozey", "joy togetherness presence"),
  soundtrack("7MC4XR9M9amdmKQr2iDF7i", "Iko Iko (My Bestie)", "Justin Wellington, Small Jam", "friendship joy togetherness"),
  soundtrack("0G3fbPbE1vGeABDEZF0jeG", "Good Times", "CHIC", "joy presence togetherness"),
  soundtrack("5RKQ5NdjSh2QzD4MaunT91", "Don't Stop Believin' (2022 Remaster)", "Journey", "hope perseverance dreams"),
  soundtrack("6FE2iI43OZnszFLuLtvvmg", "Classic", "MKTO", "love appreciation joy"),
  soundtrack("1O4YjCOOmoXJeYXL8wO0KF", "Unpack Your Heart", "Phillip Phillips", "love trust support"),
  soundtrack("58r4JuwHhXLAkttkaUZfLw", "Got to Be Real", "Cheryl Lynn", "selfWorth love confidence"),
  soundtrack("2tUBqZG2AbRi7Q0BIrVrEj", "I Wanna Dance with Somebody (Who Loves Me)", "Whitney Houston", "love joy connection"),
  soundtrack("3SnGymj6ijE2iuUfWxLo1q", "I'm Coming Out", "Diana Ross", "selfWorth freedom courage"),
  soundtrack("66S14BkJDxgkYxLl5DCqOz", "I'm Gonna Be (500 Miles)", "The Proclaimers", "love perseverance devotion"),
  soundtrack("6sxptembJVty4sNtcPMAVz", "Man! I Feel Like A Woman!", "Shania Twain", "selfWorth freedom confidence"),
  soundtrack("6gJdDnF2TzfA1WPMXuCa3x", "Proud Mary", "Tina Turner", "growth freedom resilience"),
  soundtrack("2grjqo0Frpf2okIBiifQKs", "September", "Earth, Wind & Fire", "joy memory love"),
  soundtrack("0cqRj7pUJDkTCEsJkx8snD", "Shake It Off", "Taylor Swift", "resilience selfWorth joy"),
  soundtrack("2ZNTPtYmAhN9vCwnAgqKn1", "Shout, Pts. 1 & 2", "The Isley Brothers", "joy expression togetherness"),
  soundtrack("4kbj5MwxO1bq9wjT5g9HaA", "Shut Up and Dance", "WALK THE MOON", "love joy courage"),
  soundtrack("62AuGbAkt8Ox2IrFFb8GKV", "Sweet Caroline", "Neil Diamond", "love togetherness joy"),
  soundtrack("32OlwWuMpZ6b0aN2RZOeMS", "Uptown Funk (feat. Bruno Mars)", "Mark Ronson, Bruno Mars", "confidence joy celebration"),
  soundtrack("6bNB5gxFX6Q87DbQWb8OWZ", "Waka Waka (This Time for Africa) [The Official 2010 FIFA World Cup (TM) Song] (feat. Freshlyground)", "Shakira, Freshlyground", "courage togetherness perseverance"),
  soundtrack("0ikz6tENMONtK6qGkOrU3c", "Wake Me Up Before You Go-Go", "Wham!", "love joy connection"),
  soundtrack("0YfOnJWqmAKaUvEL1QcNop", "A Change Is Gonna Come", "Sam Cooke", "hope resilience change"),
  soundtrack("6PZby1bNMj2ZEPShwQwJnL", "Hold Back The River", "James Bay", "connection resilience presence"),
  soundtrack("7tqhbajSfrz2F7E1Z75ASX", "Ain't No Mountain High Enough", "Marvin Gaye, Tammi Terrell", "love perseverance devotion"),
  soundtrack("13toFl1UwJPsRxDiD9jgtn", "As", "Stevie Wonder", "love devotion wonder"),
  soundtrack("6l8EbYRtQMgKOyc1gcDHF9", "Bridge Over Troubled Water", "Simon & Garfunkel", "kindness comfort togetherness"),
  soundtrack("1l2Xmg54EUr3TDzNIaCr1z", "Coat of Many Colors", "Dolly Parton", "gratitude selfWorth love"),
  soundtrack("1wZ7o1mZysv1l26ZWawVfW", "Freedom! '90 - Remastered", "George Michael", "freedom selfWorth courage"),
  soundtrack("2gJDyiRxxIglLXp545SPVL", "I Knew You Were Waiting (For Me)", "Aretha Franklin, George Michael", "love hope perseverance"),
  soundtrack("5LxvwujISqiB8vpRYv887S", "I Want You Back", "The Jackson 5", "love hope renewal"),
  soundtrack("7s25THrKz86DM225dOYwnr", "Respect", "Aretha Franklin", "selfWorth confidence respect"),
  soundtrack("7oOOI85fVQvVnK5ynNMdW7", "Rock with You - Single Version", "Michael Jackson", "love joy connection"),
  soundtrack("4pNiE4LCVV74vfIBaUHm1b", "Sir Duke", "Stevie Wonder", "creativity joy music"),
  soundtrack("5o5U2r5F3ojvkhLSqRbY1Y", "The One and Only", "Chesney Hawkes", "selfWorth confidence individuality"),
  soundtrack("2olVm1lHicpveMAo4AUDRB", "The Power Of Love", "Huey Lewis & The News", "love strength courage"),
  soundtrack("1Ehdm1PDlKrdfyBsjwEvd1", "Top Of The World", "Carpenters", "joy love gratitude"),
  soundtrack("0qxYx4F3vm1AOnfux6dDxP", "You Can Call Me Al", "Paul Simon", "friendship journey joy"),
  soundtrack("5sJz7lzKC8YwJQeCbWk5Ex", "A Day In My Life", "FRYDALOUX", "presence gratitude joy"),
  soundtrack("1OppEieGNdItZbE14gLBEv", "You Can't Hurry Love", "The Supremes", "love patience hope"),
  soundtrack("2u2udGmop1z67EPpr91km7", "Man in the Mirror", "Michael Jackson", "change growth kindness"),
  soundtrack("0PDCewmZCp0P5s00bptcdd", "This Will Be (An Everlasting Love)", "Natalie Cole", "love joy devotion"),
  soundtrack("4o6BgsqLIBViaGVbx5rbRk", "You Make My Dreams (Come True)", "Daryl Hall & John Oates", "love dreams joy"),
  soundtrack("5519RhpzObr9Mn3iqoeodJ", "Come and Get Your Love", "Redbone", "love confidence joy"),
  soundtrack("67INp2Tc9IqLnGy432baEN", "Get Up I Feel Like Being Like A Sex Machine", "James Brown", "confidence joy expression"),
  soundtrack("3yDhZq8f17SmumVmEyCaRN", "Give It Up", "KC & The Sunshine Band", "love joy connection"),
  soundtrack("4yrM5BVyJzy5Ed4GPO6e8j", "I Wanna Be Your Lover", "Prince", "love connection joy"),
  soundtrack("62LJFaYihsdVrrkgUOJC05", "Kiss", "Prince", "love confidence connection"),
  soundtrack("70C4NyhjD5OZUMzvWZ3njJ", "Piano Man", "Billy Joel", "togetherness compassion music"),
  soundtrack("1B8dIN7m0vNcxTZQxlRNFW", "Shake Your Tail Feather", "West End Orchestra and Singers", "joy music togetherness"),
  soundtrack("6ek9SiEj5a65WIs2EV7qiM", "Son Of A Preacher Man", "Dusty Springfield", "love memory joy"),
  soundtrack("1hu2s7qkm5bo03eODpRQO3", "Wanna Be Startin' Somethin'", "Michael Jackson", "resilience selfWorth courage"),
  soundtrack("7e89621JPkKaeDSTQ3avtg", "Sweet Home Alabama", "Lynyrd Skynyrd", "belonging gratitude joy"),
  soundtrack("0bRXwKfigvpKZUurwqAlEh", "Lovely Day", "Bill Withers", "joy gratitude presence"),
  soundtrack("5f5YqZZe34nsabun39eqo8", "Put Your Records On", "Corinne Bailey Rae", "selfWorth freedom joy"),
  soundtrack("5zCJvrT3C7cIfHsR5iG95l", "Lean on Me", "Bill Withers", "friendship support togetherness"),
  soundtrack("1lkvpmrCaXK8QtliFDcHBO", "Bubbly", "Colbie Caillat", "love joy comfort"),
  soundtrack("46IZ0fSY2mpAiktS3KOqds", "Easy On Me", "Adele", "acceptance comfort resilience"),
  soundtrack("6Uy6K3KdmUdAfelUp0SeXn", "Brave", "Sara Bareilles", "courage confidence expression"),
  soundtrack("4kP69y3GKHi9tXckfgp4bK", "For Once In My Life", "Stevie Wonder", "love gratitude hope"),
  soundtrack("4QxDOjgpYtQDxxbWPuEJOy", "L-O-V-E", "Nat King Cole", "love joy connection"),
  soundtrack("5Fpe2DMiC7BujUQeZFY6IV", "A Little Less Conversation", "Elvis Presley", "confidence expression presence"),
  soundtrack("6Ac4NVYYl2U73QiTt11ZKd", "Hooked On A Feeling", "Blue Swede, Björn Skifs", "love joy connection"),
  soundtrack("3nFJbZCHP4d9vduKjJLdBL", "Never Too Much", "Luther Vandross", "love joy devotion"),
  soundtrack("2cK7SJ2O3CqDRHeixvFKgh", "Move On Up", "Curtis Mayfield", "courage growth perseverance"),
  soundtrack("6yJxCltgtmGxIgKOS6ndnu", "Greatest Love of All", "Whitney Houston", "selfWorth courage confidence"),
  soundtrack("0snPJPxkk0MbTc0xeUvAPt", "Dancing On The Ceiling", "Lionel Richie", "joy freedom celebration"),
  soundtrack("1xupkmvtlZxfId3wXo4vAq", "Love Grows (Where My Rosemary Goes)", "Sonny Tennet", "love joy growth"),
  soundtrack("79qxwHypONUt3AFq0WPpT9", "Rainbow", "Kacey Musgraves", "hope comfort resilience"),
  soundtrack("0DwClY2t9YAWHBROMIgrXb", "Ho Hey", "The Lumineers", "love connection belonging"),
  soundtrack("6XK6Zw6JkFsHXzAcMWNiIr", "Send Me On My Way", "Rusted Root", "journey freedom joy"),
  soundtrack("4I8Nhe8qN9xgR8tosYQ5ut", "Be OK", "Ingrid Michaelson", "hope resilience comfort"),
  soundtrack("3IQF4xCQUPicbA4hWfTxPo", "I Lived", "OneRepublic", "presence courage dreams"),
  soundtrack("1YYhDizHx7PnDhAhko6cDS", "Take Me Home, Country Roads - Original Version", "John Denver", "belonging journey nature"),
  soundtrack("031tI90Tz4hlhPmvi3djr0", "It Would Be You", "Ben Rector", "love devotion connection"),
  soundtrack("3OZLF4HRzBWNIJXreuOsZI", "Only Human", "FRYDALOUX", "acceptance selfWorth connection"),
  soundtrack("7qnsOtGdKBXwRgOEoI6ZAU", "Bright Side of the Road", "Van Morrison", "hope journey joy"),
  soundtrack("0b71ZWopPmOHqVFZUetU2r", "Have I Told You Lately", "Van Morrison", "love gratitude appreciation"),
  soundtrack("6pPWRBubXOBAHnjl5ZIujB", "The Best", "Tina Turner", "love appreciation confidence"),
  soundtrack("6cjwec9ii5uLK7CDfPBYt1", "Wide Open Spaces", "The Chicks", "freedom growth courage"),
  soundtrack("5Hroj5K7vLpIG4FNCRIjbP", "Best Day Of My Life", "American Authors", "joy gratitude presence"),
  soundtrack("6t6oULCRS6hnI7rm0h5gwl", "Some Nights", "fun.", "selfWorth belonging resilience"),
  soundtrack("3B5UbSndRz907IZhhmUfLi", "Count on Me", "Bruno Mars", "friendship support trust"),
  soundtrack("5tVA6TkbaAH9QMITTQRrNv", "Free Fallin'", "Tom Petty", "freedom journey selfWorth"),
  soundtrack("4T6HLdP6OcAtqC6tGnQelG", "Everything", "Michael Bublé", "love appreciation joy"),
  soundtrack("03wrmep5c3Dr9JlOXPvFUX", "You Raise Me Up", "Celtic Woman", "support strength hope"),
  soundtrack("69vToJ9BMbbLlFZo7k7A7B", "You Are The Reason", "Calum Scott", "love devotion hope"),
  soundtrack("56sxN1yKg1dgOZXBcAHkJG", "Gone, Gone, Gone", "Phillip Phillips", "love devotion support"),
  soundtrack("1EAgPzRbK9YmdOESSMUm6P", "Home", "Phillip Phillips", "belonging support togetherness"),
  soundtrack("4ofwffwvvnbSkrMSCKQDaC", "Shotgun", "George Ezra", "freedom joy journey"),
  soundtrack("4HlFJV71xXKIGcU3kRyttv", "Hey, Soul Sister", "Train", "love appreciation joy"),
  soundtrack("15u254hThajkKs8ILIGgAw", "Where The Adventure Begins", "Tim Halperin", "journey courage possibility"),
  soundtrack("2lxBZVbkiCXC1soks2RXwV", "Love Like This", "Ben Rector", "love gratitude wonder"),
  soundtrack("5x4BgBSgr8hjmJqv7AUKTj", "Back Home", "Andy Grammer", "belonging friendship togetherness"),
  soundtrack("2QfiRTz5Yc8DdShCxG1tB2", "Johnny B. Goode", "Chuck Berry", "dreams confidence music"),
  soundtrack("1I6pKIyaBp4OebTGLJpCCC", "Perm", "Bruno Mars", "confidence joy expression"),
  soundtrack("0GONea6G2XdnHWjNZd6zt3", "Summer Of '69", "Bryan Adams", "memory dreams joy"),
  soundtrack("56lhDZNQ5J47aog6mGKeGk", "Thunder Road", "Bruce Springsteen", "hope freedom dreams"),
  soundtrack("4N0TP4Rmj6QQezWV88ARNJ", "Superstition", "Stevie Wonder", "wisdom selfWorth courage"),
  soundtrack("295j1WXVBVgI1S2iuBtwhO", "Soul Man", "Sam & Dave", "confidence joy selfWorth"),
  soundtrack("6Vmf8cIBK9pHmEQEPPAYDE", "Firework", "Katy Perry", "selfWorth courage expression"),
  soundtrack("2ZFkTA7eaFTQ7pGUOeL97e", "Budapest", "George Ezra", "love devotion togetherness"),
]);
