// Curated from GREATEST_RECORDS_-_TOP_350(ish), PARTY_TIME, and a broader
// selection of positive tracks chosen to keep every quote cycle unique.
// The pool favors positive, hopeful, affectionate, resilient, and celebratory
// themes while excluding metal, punk, hard rock, hip-hop, rap, electronic, and
// related genres; reggae is limited to upbeat crossover tracks rather than staples.
const soundtrack = (id, title, artist, themes) =>
  Object.freeze({ id, title, artist, themes: Object.freeze(themes.split(" ")) });

window.SOUNDTRACKS = Object.freeze([
  { id: "2H7PHVdQ3mXqEHXcvclTB0", title: "1999", artist: "Prince", themes: ["presence", "joy", "freedom"] },
  { id: "20I6sIOMTCkB6w7ryavxtO", title: "Call Me Maybe", artist: "Carly Rae Jepsen", themes: ["love", "courage", "joy"] },
  { id: "3K7Q9PHUWPTaknlbFPThn2", title: "Celebration", artist: "Kool & The Gang", themes: ["joy", "togetherness", "presence"] },
  { id: "6FE2iI43OZnszFLuLtvvmg", title: "Classic", artist: "MKTO", themes: ["love", "appreciation", "joy"] },
  { id: "46eu3SBuFCXWsPT39Yg3tJ", title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson", themes: ["perseverance", "joy", "love"] },
  { id: "5RKQ5NdjSh2QzD4MaunT91", title: "Don't Stop Believin' (2022 Remaster)", artist: "Journey", themes: ["hope", "perseverance", "dreams"] },
  { id: "1NHWG8zxSEypSRF3UufrnO", title: "Don't Stop Me Now", artist: "Queen", themes: ["confidence", "joy", "freedom"] },
  { id: "6W2VbtvMrDXm5vYeB7amkO", title: "Footloose", artist: "Kenny Loggins", themes: ["freedom", "joy", "courage"] },
  { id: "4y1LsJpmMti1PfRQV9AWWe", title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", themes: ["freedom", "joy", "selfWorth"] },
  { id: "0G3fbPbE1vGeABDEZF0jeG", title: "Good Times", artist: "CHIC", themes: ["joy", "presence", "togetherness"] },
  { id: "58r4JuwHhXLAkttkaUZfLw", title: "Got to Be Real", artist: "Cheryl Lynn", themes: ["selfWorth", "love", "confidence"] },
  { id: "2tUBqZG2AbRi7Q0BIrVrEj", title: "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston", themes: ["love", "joy", "connection"] },
  { id: "3SnGymj6ijE2iuUfWxLo1q", title: "I'm Coming Out", artist: "Diana Ross", themes: ["selfWorth", "freedom", "courage"] },
  { id: "67iAlVNDDdddxqSD2EZhFs", title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers", themes: ["love", "perseverance", "devotion"] },
  { id: "1ot6jEe4w4hYnsOPjd3xKQ", title: "I'm So Excited", artist: "The Pointer Sisters", themes: ["joy", "hope", "love"] },
  { id: "6FMIVQPZg9cmMY8hPxAacD", title: "Let's Go Crazy", artist: "Prince", themes: ["presence", "freedom", "courage"] },
  { id: "3koCCeSaVUyrRo3N2gHrd8", title: "Let's Groove", artist: "Earth, Wind & Fire", themes: ["joy", "togetherness", "connection"] },
  { id: "6sxptembJVty4sNtcPMAVz", title: "Man! I Feel Like A Woman!", artist: "Shania Twain", themes: ["selfWorth", "freedom", "confidence"] },
  { id: "4PTG3Z6ehGkBFwjybzWkR8", title: "Never Gonna Give You Up", artist: "Rick Astley", themes: ["love", "devotion", "trust"] },
  { id: "6gJdDnF2TzfA1WPMXuCa3x", title: "Proud Mary", artist: "Tina Turner", themes: ["growth", "freedom", "resilience"] },
  { id: "2grjqo0Frpf2okIBiifQKs", title: "September", artist: "Earth, Wind & Fire", themes: ["joy", "memory", "love"] },
  { id: "0cqRj7pUJDkTCEsJkx8snD", title: "Shake It Off", artist: "Taylor Swift", themes: ["resilience", "selfWorth", "joy"] },
  { id: "2ZNTPtYmAhN9vCwnAgqKn1", title: "Shout, Pts. 1 & 2", artist: "The Isley Brothers", themes: ["joy", "expression", "togetherness"] },
  { id: "4kbj5MwxO1bq9wjT5g9HaA", title: "Shut Up and Dance", artist: "WALK THE MOON", themes: ["love", "joy", "courage"] },
  { id: "62AuGbAkt8Ox2IrFFb8GKV", title: "Sweet Caroline", artist: "Neil Diamond", themes: ["love", "togetherness", "joy"] },
  { id: "32OlwWuMpZ6b0aN2RZOeMS", title: "Uptown Funk (feat. Bruno Mars)", artist: "Mark Ronson, Bruno Mars", themes: ["confidence", "joy", "celebration"] },
  { id: "6bNB5gxFX6Q87DbQWb8OWZ", title: "Waka Waka (This Time for Africa)", artist: "Shakira, Freshlyground", themes: ["courage", "togetherness", "perseverance"] },
  { id: "0ikz6tENMONtK6qGkOrU3c", title: "Wake Me Up Before You Go-Go", artist: "Wham!", themes: ["love", "joy", "connection"] },
  { id: "5IKLwqBQG6KU6MP2zP80Nu", title: "We Are Family - 1995 Remaster", artist: "Sister Sledge", themes: ["togetherness", "belonging", "joy"] },
  { id: "0YfOnJWqmAKaUvEL1QcNop", title: "A Change Is Gonna Come", artist: "Sam Cooke", themes: ["hope", "resilience", "change"] },
  { id: "7tqhbajSfrz2F7E1Z75ASX", title: "Ain't No Mountain High Enough", artist: "Marvin Gaye, Tammi Terrell", themes: ["love", "perseverance", "devotion"] },
  { id: "3cfOd4CMv2snFaKAnMdnvK", title: "All Star", artist: "Smash Mouth", themes: ["selfWorth", "confidence", "growth"] },
  { id: "13toFl1UwJPsRxDiD9jgtn", title: "As", artist: "Stevie Wonder", themes: ["love", "devotion", "wonder"] },
  { id: "6l8EbYRtQMgKOyc1gcDHF9", title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", themes: ["kindness", "comfort", "togetherness"] },
  { id: "1l2Xmg54EUr3TDzNIaCr1z", title: "Coat of Many Colors", artist: "Dolly Parton", themes: ["gratitude", "selfWorth", "love"] },
  { id: "0HEmnAUT8PHznIAAmVXqFJ", title: "Faith - Remastered", artist: "George Michael", themes: ["hope", "love", "courage"] },
  { id: "1wZ7o1mZysv1l26ZWawVfW", title: "Freedom! '90 - Remastered", artist: "George Michael", themes: ["freedom", "selfWorth", "courage"] },
  { id: "2gJDyiRxxIglLXp545SPVL", title: "I Knew You Were Waiting (For Me)", artist: "Aretha Franklin, George Michael", themes: ["love", "hope", "perseverance"] },
  { id: "5LxvwujISqiB8vpRYv887S", title: "I Want You Back", artist: "The Jackson 5", themes: ["love", "hope", "renewal"] },
  { id: "7s25THrKz86DM225dOYwnr", title: "Respect", artist: "Aretha Franklin", themes: ["selfWorth", "confidence", "respect"] },
  { id: "7oOOI85fVQvVnK5ynNMdW7", title: "Rock with You - Single Version", artist: "Michael Jackson", themes: ["love", "joy", "connection"] },
  { id: "4pNiE4LCVV74vfIBaUHm1b", title: "Sir Duke", artist: "Stevie Wonder", themes: ["creativity", "joy", "music"] },
  { id: "5o5U2r5F3ojvkhLSqRbY1Y", title: "The One and Only", artist: "Chesney Hawkes", themes: ["selfWorth", "confidence", "individuality"] },
  { id: "2olVm1lHicpveMAo4AUDRB", title: "The Power Of Love", artist: "Huey Lewis & The News", themes: ["love", "strength", "courage"] },
  { id: "1Ehdm1PDlKrdfyBsjwEvd1", title: "Top Of The World", artist: "Carpenters", themes: ["joy", "love", "gratitude"] },
  { id: "0qxYx4F3vm1AOnfux6dDxP", title: "You Can Call Me Al", artist: "Paul Simon", themes: ["friendship", "journey", "joy"] },
  { id: "1OppEieGNdItZbE14gLBEv", title: "You Can't Hurry Love", artist: "The Supremes", themes: ["love", "patience", "hope"] },
  { id: "687YZan9Gol1UVvbpUSO6Y", title: "I Wish", artist: "Stevie Wonder", themes: ["memory", "joy", "gratitude"] },
  { id: "3zYpRGnnoegSpt3SguSo3W", title: "Off the Wall", artist: "Michael Jackson", themes: ["freedom", "joy", "selfWorth"] },
  { id: "5o37x6LpNSec4jSfPIChsQ", title: "We Got The Beat - 2011 Remaster", artist: "The Go-Go's", themes: ["music", "joy", "togetherness"] },

  soundtrack("0mYXRQpTGjaLJt1l9MY4ps", "Man I Need", "Olivia Dean", "love connection hope"),
  soundtrack("4yqx7PuUrpWmuqkNZ98yH7", "Man In The Mirror", "Michael Jackson", "change growth kindness"),
  soundtrack("2FQrifJ1N335Ljm3TjTVVf", "A Bar Song (Tipsy)", "Shaboozey", "joy togetherness presence"),
  soundtrack("7zrR8FQzW5FJ9b5ONWjAdU", "MmmBop", "Hanson", "love connection presence"),
  soundtrack("117Ar0q7gX4Z7PgX1xmWMK", "This Will Be (An Everlasting Love)", "Natalie Cole", "love joy devotion"),
  soundtrack("5irxhEIVREkA4BFT3wCiHR", "You Make My Dreams (Come True)", "Daryl Hall & John Oates", "love dreams joy"),
  soundtrack("0WF0CUhQpCnbIWkauzd3PT", "Come And Get Your Love", "Redbone", "love confidence joy"),
  soundtrack("1KZyVnyptQcPzkx7ELCnZC", "Hold Back The River", "James Bay", "connection resilience presence"),

  soundtrack("6b8Be6ljOzmkOmFslEb23P", "24K Magic", "Bruno Mars", "confidence joy celebration"),
  soundtrack("3BovdzfaX4jb5KFQwoPfAw", "Beat It", "Michael Jackson", "courage peace selfWorth"),
  soundtrack("6hTcuIQa0sxrrByu9wTD7s", "Born to Run", "Bruce Springsteen", "freedom dreams courage"),
  soundtrack("3MrWxJaD2AT0W9DjWF64Vm", "Come On Eileen", "Dexys Midnight Runners", "love courage joy"),
  soundtrack("67INp2Tc9IqLnGy432baEN", "Get Up I Feel Like Being Like A Sex Machine", "James Brown", "confidence joy expression"),
  soundtrack("3yDhZq8f17SmumVmEyCaRN", "Give It Up", "KC & The Sunshine Band", "love joy connection"),
  soundtrack("64Ny7djQ6rNJspquof2KoX", "Hound Dog", "Elvis Presley", "selfWorth confidence freedom"),
  soundtrack("4yrM5BVyJzy5Ed4GPO6e8j", "I Wanna Be Your Lover", "Prince", "love connection joy"),
  soundtrack("2QfiRTz5Yc8DdShCxG1tB2", "Johnny B. Goode", "Chuck Berry", "dreams confidence music"),
  soundtrack("62LJFaYihsdVrrkgUOJC05", "Kiss", "Prince", "love confidence connection"),
  soundtrack("0uMMLry3hzWGn3q3loqMkm", "La Bamba", "Los Lobos", "joy togetherness music"),
  soundtrack("2v7ywbUzCgcVohHaKUcacV", "Like a Prayer", "Madonna", "love faith wonder"),
  soundtrack("0Ph6L4l8dYUuXFmb71Ajnd", "Livin' la Vida Loca", "Ricky Martin", "joy freedom presence"),
  soundtrack("7cyjVwpuFhjY2ZN3ckfo2C", "New Eyes", "Nicklas Sahl", "love growth wonder"),
  soundtrack("1KGi9sZVMeszgZOWivFpxs", "No Scrubs", "TLC", "selfWorth confidence respect"),
  soundtrack("58cAopfBOtm1Sgifx99jtR", "Papa's Got A Brand New Bag - Pt. 1", "James Brown", "change confidence joy"),
  soundtrack("1I6pKIyaBp4OebTGLJpCCC", "Perm", "Bruno Mars", "confidence joy expression"),
  soundtrack("70C4NyhjD5OZUMzvWZ3njJ", "Piano Man", "Billy Joel", "togetherness compassion music"),
  soundtrack("5uuJruktM9fMdN9Va0DUMl", "Play That Funky Music", "Wild Cherry", "music joy togetherness"),
  soundtrack("1uvyZBs4IZYRebHIB1747m", "Purple Rain", "Prince", "love forgiveness hope"),
  soundtrack("51q3nDYWAqPY4hlgKEbP6j", "Rhythm Nation", "Janet Jackson", "togetherness change hope"),
  soundtrack("4SDWMFvYJKtK1QPhIOeZhd", "Royals", "Lorde", "selfWorth friendship confidence"),
  soundtrack("0TK2YIli7K1leLovkQiNik", "Señorita", "Shawn Mendes, Camila Cabello", "love connection joy"),
  soundtrack("1B8dIN7m0vNcxTZQxlRNFW", "Shake Your Tail Feather", "West End Orchestra and Singers", "joy music togetherness"),
  soundtrack("7qiZfU4dY1lWllzX7mPBI3", "Shape of You", "Ed Sheeran", "love attraction connection"),
  soundtrack("5R9a4t5t5O0IsznsrKPVro", "Single Ladies (Put a Ring on It)", "Beyoncé", "selfWorth confidence respect"),
  soundtrack("6ek9SiEj5a65WIs2EV7qiM", "Son Of A Preacher Man", "Dusty Springfield", "love memory joy"),
  soundtrack("0ug5NqcwcFR2xrfTkc7k8e", "Style", "Taylor Swift", "love connection confidence"),
  soundtrack("0GONea6G2XdnHWjNZd6zt3", "Summer Of '69", "Bryan Adams", "memory dreams joy"),
  soundtrack("56lhDZNQ5J47aog6mGKeGk", "Thunder Road", "Bruce Springsteen", "hope freedom dreams"),
  soundtrack("3pbtBomO4Zt5gGiqsYeiBH", "Upside Down", "Diana Ross", "love joy connection"),
  soundtrack("1hu2s7qkm5bo03eODpRQO3", "Wanna Be Startin' Somethin'", "Michael Jackson", "resilience selfWorth courage"),
  soundtrack("6OnfBiiSc9RGKiBKKtZXgQ", "We Built This City", "Starship", "music togetherness confidence"),
  soundtrack("5yQ9iMZXGcr5rlO4hoLsP4", "What'd I Say, Pt. 1 & 2", "Ray Charles", "joy love expression"),
  soundtrack("0K9tfzrxJyCQIf7oAlPwaK", "YA YA", "Beyoncé", "freedom joy resilience"),

  soundtrack("7e89621JPkKaeDSTQ3avtg", "Sweet Home Alabama", "Lynyrd Skynyrd", "belonging gratitude joy"),
  soundtrack("6x4tKaOzfNJpEJHySoiJcs", "Mambo No. 5 (a Little Bit of...)", "Lou Bega", "joy music celebration"),
  soundtrack("4N0TP4Rmj6QQezWV88ARNJ", "Superstition", "Stevie Wonder", "wisdom selfWorth courage"),
  soundtrack("3Um9toULmYFGCpvaIPFw7l", "What's Going On", "Marvin Gaye", "kindness peace togetherness"),
  soundtrack("1O1mCVN5hue4lOOqd5EysZ", "Living For The City", "Stevie Wonder", "resilience courage hope"),
  soundtrack("4W4wYHtsrgDiivRASVOINL", "Love Shack", "The B-52's", "love joy togetherness"),
  soundtrack("0c2OhVdRZV2C6wfiBtT32D", "Walking On Sunshine", "Katrina & The Waves", "joy hope presence"),
  soundtrack("24cD8nSAmryP9F35MYZ60H", "Lovely Day", "Bill Withers", "joy gratitude presence"),
  soundtrack("14oe35OW7EhfZrbGvP69m5", "Put Your Records On", "Corinne Bailey Rae", "selfWorth freedom joy"),
  soundtrack("3zUJLUJcYjGTBzN2yBNoIk", "Lean on Me", "Bill Withers", "friendship support togetherness"),
  soundtrack("1qCQTy0fTXerET4x8VHyr9", "What A Wonderful World", "Louis Armstrong", "wonder gratitude nature"),
  soundtrack("7BqBn9nzAq8spo5e7cZ0dJ", "Just the Way You Are", "Bruno Mars", "love appreciation acceptance"),
  soundtrack("1pKpSdrKMW0Bn9sHPqmuAY", "Better Together", "Jack Johnson", "love togetherness connection"),
  soundtrack("1HLIkqfnhYNEVPFfKsF5rw", "Banana Pancakes", "Jack Johnson", "love presence comfort"),
  soundtrack("0GW9IVuYv9ZsCa1kjGGYH2", "Bubbly", "Colbie Caillat", "love joy comfort"),
  soundtrack("56xBuCeP12ve4gPm3nD7TQ", "Brave", "Sara Bareilles", "courage confidence expression"),
  soundtrack("1qhp5owrFGeZ5Jgin28nwR", "You've Got a Friend", "Carole King", "friendship comfort togetherness"),
  soundtrack("58KeNIwSX4njezDBQhRFRJ", "Beautiful", "Carole King", "selfWorth wonder appreciation"),
  soundtrack("7kn6dNP2JPSWueS9S0DQRj", "Signed, Sealed, Delivered (I'm Yours)", "Stevie Wonder", "love devotion joy"),
  soundtrack("3jNLTzscecLjVE1VLBYueV", "For Once In My Life", "Stevie Wonder", "love gratitude hope"),
  soundtrack("3vqlZUIT3rEmLaYKDBfb4Q", "Isn't She Lovely", "Stevie Wonder", "love appreciation joy"),
  soundtrack("6Su7cLq5RbcwxkoBliLSXg", "Love Train", "The O'Jays", "love togetherness hope"),
  soundtrack("5RdhBLmB4DyFHLglRrfx63", "I'll Be There", "The Jackson 5", "love support devotion"),
  soundtrack("4VuHrh3RbEPWSvdTrmpUxi", "My Girl", "The Temptations", "love joy appreciation"),
  soundtrack("1udKn1oNKYQSQ9OmiIWCMu", "Do You Believe in Magic", "The Lovin' Spoonful", "wonder music joy"),
  soundtrack("2PuFuBXRBxD0WyNI8IxgZd", "L-O-V-E", "Nat King Cole", "love joy connection"),
  soundtrack("5RKZ9zCtLjBLTea7qkSFqr", "I'm a Believer", "The Monkees", "love hope joy"),
  soundtrack("1nAO0D1Z9esA0qlWq5D3Ff", "Happy Together", "The Turtles", "love togetherness joy"),
  soundtrack("5otWzkqD4RKYYXsU3dlIxM", "Love Grows (Where My Rosemary Goes)", "Edison Lighthouse", "love joy growth"),
  soundtrack("6CZdlDDL7k1uAhriRhQbLk", "Hooked on a Feeling", "Blue Swede", "love joy connection"),
  soundtrack("3M3SBRzq5mWfYPXZdOYPG4", "Sugar, Sugar", "The Archies", "love joy appreciation"),
  soundtrack("3fnPQet0rmyzHqtcLyjDdi", "Never Too Much", "Luther Vandross", "love joy devotion"),
  soundtrack("3gCRfLVxgddCIsqoNLtRUw", "Move On Up", "Curtis Mayfield", "courage growth perseverance"),
  soundtrack("6MIyNL9iSMvPh13oZRMyL8", "Greatest Love of All", "Whitney Houston", "selfWorth courage confidence"),
  soundtrack("3bTw40U34YT29zpF6k6dgP", "Dancing On The Ceiling", "Lionel Richie", "joy freedom celebration"),
  soundtrack("3v2l8iiKAhl4zCXmHtFlKD", "All Night Long (All Night)", "Lionel Richie", "joy togetherness celebration"),
  soundtrack("6b5WMDnhpqw6UEtIfTMGlh", "Stronger (What Doesn't Kill You)", "Kelly Clarkson", "resilience courage strength"),
  soundtrack("27tNWlhdAryQY04Gb2ZhUI", "Roar", "Katy Perry", "courage confidence selfWorth"),
  soundtrack("0AuaOZpWQiqsawSR2zxP1P", "Rainbow", "Kacey Musgraves", "hope comfort resilience"),
  soundtrack("5EYWGM3Ns3iYew8ws0FatB", "This Kiss", "Faith Hill", "love joy wonder"),
  soundtrack("0hKF8N8aflF1uDzEEnPr2j", "Life Is A Highway", "Tom Cochrane", "journey courage joy"),
  soundtrack("4hgnmFIXfzG1HMJuETKwGV", "Ho Hey", "The Lumineers", "love connection belonging"),
  soundtrack("0R4vpVecKzG3QNjB5rj4TQ", "Home", "Edward Sharpe & The Magnetic Zeros", "love belonging togetherness"),
  soundtrack("29lK4ljEzuiyYding0nBQ8", "Send Me On My Way", "Rusted Root", "journey freedom joy"),
  soundtrack("2A0wyfxedHlikEjlAmISvB", "Be OK", "Ingrid Michaelson", "hope resilience comfort"),
  soundtrack("29yLZTWlWFtAKjVpMQzTEK", "I Lived", "OneRepublic", "presence courage dreams"),
  soundtrack("6OtCIsQZ64Vs1EbzztvAv4", "Good Life", "OneRepublic", "gratitude joy presence"),
  soundtrack("1mPhBlDYlxw4nDrbtt0kqu", "Keep Your Head Up", "Andy Grammer", "hope resilience courage"),
  soundtrack("3g3sMZrjQWfktLDTF2TEQM", "Good To Be Alive (Hallelujah)", "Andy Grammer", "gratitude joy presence"),
  soundtrack("4ofwffwvvnbSkrMSCKQDaC", "Shotgun", "George Ezra", "freedom joy journey"),
  soundtrack("43mqq5c3ZJtnJ90TNmqzI3", "You're Still The One", "Shania Twain", "love devotion perseverance"),
  soundtrack("6K1sUckiJLXhsyte2yNFTQ", "Love Story", "Taylor Swift", "love hope courage"),
  soundtrack("1wHtNNUcCYfCl7UEEzgm7H", "Take Me Home, Country Roads", "John Denver", "belonging journey nature"),
  soundtrack("295j1WXVBVgI1S2iuBtwhO", "Soul Man", "Sam & Dave", "confidence joy selfWorth"),
  soundtrack("62HHRYPiD3lmH6imdsTc5U", "I Got You (I Feel Good)", "James Brown & The Famous Flames", "joy gratitude love"),
  soundtrack("3P5yc4ZllzHB8ps1r27czE", "Shining Star", "Earth, Wind & Fire", "selfWorth confidence wonder"),
  soundtrack("6LrIVgrtvLrBu7x2o0d3yU", "Sing a Song", "Earth, Wind & Fire", "music joy expression"),
  soundtrack("5qyq1H5OPMlfuvZQ1wQNo7", "(Your Love Keeps Lifting Me) Higher & Higher", "Jackie Wilson", "love hope growth"),
  soundtrack("5s9JR33RPhtG5ebBXPXQ4c", "Baby Love", "The Supremes", "love joy connection"),
  soundtrack("64ke2cBs6nFgcnBxw3jMEr", "Dancing In The Street", "Martha Reeves & The Vandellas", "joy togetherness freedom"),
  soundtrack("4K3JmrYsSUxATQfKdZbGTq", "My Guy", "Mary Wells", "love devotion trust"),
  soundtrack("0o6sCUtTDTpnWxsWSlAsKt", "I Can't Help Myself (Sugar Pie, Honey Bunch)", "Four Tops", "love joy connection"),
  soundtrack("0ia3DCM0rSD77QM4c32IO4", "Feeling Good", "Nina Simone", "renewal confidence freedom"),
  soundtrack("6GR0vtHHsegLbcP4kzfY4y", "Don't Worry Be Happy", "Bobby McFerrin", "hope comfort joy"),
  soundtrack("4KqBoq7MoDJeVsvUHTjXCM", "Sweet Pea", "Amos Lee", "love joy appreciation"),
  soundtrack("6d4FWjx72iuRWzn1HwywLK", "Colors", "Black Pumas", "wonder beauty gratitude"),
  soundtrack("4dgyaJbtHpxTG6HXstl4eN", "Windows Are Rolled Down", "Amos Lee", "freedom journey presence"),
  soundtrack("43ddJFnP8m3PzNJXiHuiyJ", "The Way I Am", "Ingrid Michaelson", "love acceptance comfort"),
  soundtrack("1jyddn36UN4tVsJGtaJfem", "You Are the Best Thing", "Ray LaMontagne", "love appreciation gratitude"),
  soundtrack("6UMuTsckKbcRtsb3RIoVF2", "Brand New", "Ben Rector", "renewal joy love"),
  soundtrack("7qnsOtGdKBXwRgOEoI6ZAU", "Bright Side of the Road", "Van Morrison", "hope journey joy"),
  soundtrack("6026NhQnQy2I5RbiwwFYxH", "Have I Told You Lately", "Van Morrison", "love gratitude appreciation"),
  soundtrack("4CNL4GBNTdVIU5Nk6hB4LC", "Brown Eyed Girl", "Van Morrison", "love memory joy"),
  soundtrack("709vwRjxkfgmHnHiqM9Gyx", "The Best", "Tina Turner", "love appreciation confidence"),
  soundtrack("3kCz5Nmea6VHqzrAjYFH1S", "Wide Open Spaces", "The Chicks", "freedom growth courage"),
  soundtrack("5vaqvUp2GDqkP6WuxkpTtw", "Suddenly I See", "KT Tunstall", "confidence selfWorth inspiration"),
  soundtrack("37d6CzqLhOKUNxvzEOMlYS", "Unwritten", "Natasha Bedingfield", "growth courage possibility"),
  soundtrack("5Hroj5K7vLpIG4FNCRIjbP", "Best Day Of My Life", "American Authors", "joy gratitude presence"),
  soundtrack("5a3HBWgUOXQz6ZyjhLweKh", "Geronimo", "Sheppard", "courage freedom joy"),
  soundtrack("6Vmf8cIBK9pHmEQEPPAYDE", "Firework", "Katy Perry", "selfWorth courage expression"),
  soundtrack("7l1qvxWjxcKpB9PCtBuTbU", "Count on Me", "Bruno Mars", "friendship support trust"),
  soundtrack("5DLnSTGOoe5jM8b1yPI8si", "Everything", "Michael Bublé", "love appreciation joy"),
  soundtrack("3OJLRr12Vk4lIo1KWpc4qK", "Smile", "Nat King Cole", "hope resilience comfort"),
  soundtrack("33jt3kYWjQzqn3xyYQ5ZEh", "Cheek To Cheek", "Ella Fitzgerald, Louis Armstrong", "love joy connection"),
  soundtrack("3QpPpZhs1Kuo1MIxTkkH5x", "Dream A Little Dream Of Me", "Ella Fitzgerald, Louis Armstrong", "love dreams comfort"),
  soundtrack("3DqHJrQxvvlA5ZBrztd0El", "The Best Is Yet To Come", "Frank Sinatra, Count Basie", "hope confidence dreams"),
  soundtrack("7MC4XR9M9amdmKQr2iDF7i", "Iko Iko (My Bestie)", "Justin Wellington, Small Jam", "friendship joy togetherness"),
  soundtrack("21kYeU7raNOB1P6rP3ozdj", "I Can See Clearly Now", "Johnny Nash", "hope resilience renewal"),
  soundtrack("4idMI5MaiYWZnQ76wPTlcA", "Thank You For Being A Friend", "Andrew Gold", "friendship gratitude togetherness"),
  soundtrack("66iKqUazBbTlAEjcZrpDkD", "What A Diff'rence A Day Made", "Dinah Washington", "love renewal gratitude"),
  soundtrack("2MKXUXZIViCGpoFyysFpoj", "Coming Home", "Sheppard", "belonging togetherness joy"),
  soundtrack("20S0KRq4z2v2Utym0C246s", "Gone, Gone, Gone", "Phillip Phillips", "love devotion support"),
  soundtrack("51AJFWAg4QIcerucO5xWQI", "Home", "Phillip Phillips", "belonging support togetherness"),
  soundtrack("6XoOJadn9iThTMQYXyT4Fj", "Unpack Your Heart", "Phillip Phillips", "love trust support"),
  soundtrack("2RiBogNRfulkNf7fVbPOrJ", "Saturday Sun", "Vance Joy", "love joy presence"),
  soundtrack("5YqdiryRmdAzYFlxo43hAJ", "Missing Piece", "Vance Joy", "love connection belonging"),
  soundtrack("1JGb1d20y682oIHSwxk1Z7", "Fire and the Flood", "Vance Joy", "love devotion connection"),
  soundtrack("2ZFkTA7eaFTQ7pGUOeL97e", "Budapest", "George Ezra", "love devotion togetherness"),
  soundtrack("4HlFJV71xXKIGcU3kRyttv", "Hey, Soul Sister", "Train", "love appreciation joy"),
  soundtrack("0KAiuUOrLTIkzkpfpn9jb9", "Drive By", "Train", "love devotion confidence"),
  soundtrack("0YCWGi0gEYT9u4xbbNEp5V", "Renegades", "X Ambassadors", "freedom courage togetherness"),
  soundtrack("7AonnmPTczSzmqPs32Po69", "Be Okay", "Oh Honey", "hope resilience joy"),
  soundtrack("0Cd4j6FDoH6WydnNUYysQR", "I Just Wanna Shine", "Fitz and The Tantrums", "confidence selfWorth joy"),
  soundtrack("15u254hThajkKs8ILIGgAw", "Where The Adventure Begins", "Tim Halperin", "journey courage possibility"),
  soundtrack("3g3sMZrjQWfktLDTF2TEQM", "Good To Be Alive (Hallelujah)", "Andy Grammer", "joy gratitude presence"),
  soundtrack("1mPhBlDYlxw4nDrbtt0kqu", "Keep Your Head Up", "Andy Grammer", "hope resilience courage"),
  soundtrack("5x4BgBSgr8hjmJqv7AUKTj", "Back Home", "Andy Grammer", "belonging friendship togetherness"),
]);
